# Generated by Django 3.2.7 on 2022-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('_1h', models.IntegerField()),
                ('_24h', models.IntegerField()),
                ('_7d', models.IntegerField()),
                ('market_cap', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
                ('circulating_supply', models.BigIntegerField()),
            ],
        ),
    ]
