# Generated by Django 3.2.7 on 2022-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_auto_20220925_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencymodel',
            name='Price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrencymodel',
            name='_1h',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrencymodel',
            name='_24h',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrencymodel',
            name='_7d',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrencymodel',
            name='circulating_supply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrencymodel',
            name='market_cap',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrencymodel',
            name='volume',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
